# Generated by Django 5.2.6 on 2026-07-26 08:26

import apps.users.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated_at"),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        unique=True,
                        validators=[apps.users.validators.validate_telegram_id],
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Username"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Last name"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("uz", "Uzbek"), ("en", "English"), ("ru", "Russian")],
                        default="uz",
                        max_length=5,
                        verbose_name="Language",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("student", "Student"), ("admin", "Admin")],
                        default="student",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "xp",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[apps.users.validators.validate_xp],
                        verbose_name="Experience",
                    ),
                ),
                ("level", models.PositiveIntegerField(default=1, verbose_name="Level")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Last activity"
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
    ]
