# Generated by Django 5.2.6 on 2026-08-02 19:06

import apps.achievements.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_user_deleted_at_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            apps.achievements.validators.validate_achievement_name
                        ],
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "required_level",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            apps.achievements.validators.validate_required_level
                        ],
                        verbose_name="Required level",
                    ),
                ),
                (
                    "xp_reward",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[apps.achievements.validators.validate_xp_reward],
                        verbose_name="XP reward",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, default="🏆", max_length=20, verbose_name="Icon"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
                "db_table": "achievements",
                "ordering": ["required_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "earned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Earned at"),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="achievements.achievement",
                        verbose_name="Achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="users.user",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Achievement",
                "verbose_name_plural": "User Achievements",
                "db_table": "user_achievements",
                "ordering": ["-earned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "achievement"), name="unique_user_achievement"
                    )
                ],
            },
        ),
    ]
